# CloudOps ROI Assessment Configuration

data_source:
  type: "datadog"  # datadog, splunk, newrelic, prometheus
  api_key: "${DATADOG_API_KEY}"
  app_key: "${DATADOG_APP_KEY}"

analysis:
  start_date: "2024-01-01"
  end_date: "2024-12-31"
  timeline_months: 36

aws_services:
  - "cloudwatch"
  - "systems_manager" 
  - "config"

# Cost assumptions (override with actual data)
cost_assumptions:
  engineer_hourly_rate: 100
  revenue_per_hour_downtime: 10000
  compliance_violation_cost: 50000
  security_incident_cost: 100000

# Industry benchmarks
benchmarks:
  target_mttr_improvement: 0.6  # 60% improvement
  compliance_improvement: 0.8   # 80% reduction in violations  
  security_improvement: 0.7     # 70% reduction in incidents
